function draw_monkey_choice_guide(visual_opt, game_opt, curr_trial_data)
    % Extract eel information based on the current trial data
    [left_eel_curr_pos, right_eel_curr_pos, ...
          ~,~ , ...
          left_eel_original_potent, right_eel_original_potent, ...
          left_eel_color, right_eel_color, ...
          ~, ~] = ...
          check_eel_side_info(curr_trial_data, game_opt);

    % Draw the eels based on the extracted information
    draw_eel(left_eel_curr_pos, left_eel_color, game_opt.eel_sz * 2, visual_opt, left_eel_original_potent, game_opt);
    draw_eel(right_eel_curr_pos, right_eel_color, game_opt.eel_sz * 2, visual_opt, right_eel_original_potent, game_opt);
end

